### ISSUE TITLE
LaTeX resume generator

### ISSUE THREAD

**Issue by OrangeHoopla** [SeanDaBlack/KelloggBot#30]
Thinking it might help obfuscate applications if each resume is custom and aligns with the rest of the data present. Willing to work on it just want to know if its something worth completing first

**Comment by tabrown2000** [comment]
Pull request #17 has used poppler (external pdf generator) to generate fake pdf resumes with randomized data. You could use some of those dictionaries as a base. The way it's currently written, the pdf is converted to a png using pdf2image and submitted as a png rather than a pdf. 

I've changed my local copy to submit a mixture of pdfs and pngs with an assortment of file naming schemes. LaTeX could be another good way to generate pdfs. Ultimately, if it could be done without an external dependency, that'd be ideal.

**Comment by virtadpt** [comment]
You may find the information in this birbsite thread of use:

https://twitter.com/Coding_Career/status/1454293034179317764

**Comment by KathrynElrod** [comment]
> I've changed my local copy to submit a mixture of pdfs and pngs with an assortment of file naming schemes. LaTeX could be another good way to generate pdfs. Ultimately, if it could be done without an external dependency, that'd be ideal.

You've had success submitting as PDFs? I had to add the PNG conversion because uploading a PDF auto-populated some new fields and so required more interaction with the page.

**Comment by KathrynElrod** [comment]
I hadn't thought of using LaTeX to generate the resumes, I really like that method rather than the library I used. Plus, we could download a bunch of resume templates (https://www.overleaf.com/gallery/tagged/cv), modify them to be auto-fillable by the script, and submit much better looking resumes. Hmm...

**Comment by tabrown2000** [comment]
> You've had success submitting as PDFs? I had to add the PNG conversion because uploading a PDF auto-populated some new fields and so required more interaction with the page.

Just submitted a PR #48 to show how I did it
